run:
  timeout: 15m
  issues-exit-code: 1
  modules-download-mode: readonly
issues:
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - typecheck
    - path: tests/mocks\.go
      linters:
        - typecheck

linters:
  disable-all: true
  enable:
    - gosec
    - goconst
    - gofmt
    - govet
    - ineffassign
    - lll
    - gosimple
    - staticcheck
    - unused
    - misspell
    - staticcheck
    - unconvert
    - unused
linters-settings:
  goconst:
    min-len: 4 # ignore "gcp" and "aws"